#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Meta WhatsApp Coexistence + Cloud API for Dave (dealer-ledger-pro)
# ──────────────────────────────────────────────────────────────────────────
# Values are NOT persisted to .env. They go into the app's encrypted store
# (Settings → AI Sales Agent → WhatsApp Cloud API), which writes them to
# salesAgentPrivate/{companyId} via the salesAgentSavePrivate function.
# ENV_FILE is only used so a re-run remembers the non-secret ids.

ENV_FILE="${ENV_FILE:-.whatsapp-setup.local}"
TOTAL_STAGES=7
WEBHOOK_URL="https://us-central1-motor-ledger-pro.cloudfunctions.net/salesAgentWhatsAppWebhook"
APP_URL="https://motor-ledger-pro.web.app/app/settings"

banner "Dave — WhatsApp (Meta Coexistence) setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Meta Business Manager — confirm the account is clear"
say "Meta emailed on 27 Aug 2026 that Radlett Cars' advertising access was reinstated."
open_url "https://business.facebook.com/settings/info"
step "Check the 'Radlett Cars' business shows no restriction banner at the top."
step "Open Security Centre (left menu) — if it asks to verify the business, start it now; WhatsApp needs a verified business to send templates at scale."
pause "Account clear (or verification submitted)? Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Meta app — add the WhatsApp product"
open_url "https://developers.facebook.com/apps/"
step "Pick your app (or Create App → type 'Business' → name 'Radlett Cars Dave' → attach the Radlett Cars business portfolio)."
step "In the app dashboard → 'Add product' → WhatsApp → Set up. Choose the Radlett Cars business portfolio when asked."
step "App settings → Basic: copy the App ID and click Show on App Secret."
ask META_APP_ID "Paste the App ID:"
ask_secret META_APP_SECRET "Paste the App Secret (hidden):"
write_env META_APP_ID "$META_APP_ID"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Coexistence — link your existing WhatsApp Business number"
say "This keeps the WhatsApp Business app on your phone working AND lets the Cloud API use the same number."
warn "Do NOT 'Add phone number' with a fresh number. Use the Coexistence flow so the existing number is shared."
open_url "https://business.facebook.com/wa/manage/phone-numbers/"
step "WhatsApp Manager → Phone numbers → 'Add phone number' → choose 'Use a number already on the WhatsApp Business app' (Coexistence)."
step "On your PHONE: WhatsApp Business → Settings → Business tools → 'Connect to Meta / Cloud API' (wording varies) and scan the QR code shown on screen."
note "If the option is missing on the phone, update WhatsApp Business from the Play Store — Coexistence needs a recent build."
step "When it says Connected, the number appears in WhatsApp Manager. Click it and copy the Phone number ID and the WhatsApp Business Account ID (WABA ID) shown in the details."
ask WA_PHONE_NUMBER_ID "Paste the Phone number ID:"
ask WA_BUSINESS_ACCOUNT_ID "Paste the WhatsApp Business Account ID:"
write_env WA_PHONE_NUMBER_ID "$WA_PHONE_NUMBER_ID"
write_env WA_BUSINESS_ACCOUNT_ID "$WA_BUSINESS_ACCOUNT_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Permanent access token (System User)"
say "Temporary tokens from the app dashboard expire in 24h. Dave needs a permanent System User token."
open_url "https://business.facebook.com/settings/system-users"
step "Add → name 'dave-agent', role Admin → Create."
step "Assign assets → Apps → tick your app → Full control. Then Assign assets → WhatsApp accounts → tick Radlett Cars → Full control."
step "Generate token → pick your app → expiry 'Never' → tick permissions whatsapp_business_messaging and whatsapp_business_management → Generate → copy it (shown once)."
ask_secret WA_ACCESS_TOKEN "Paste the permanent access token (hidden):"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Save credentials into the app"
VERIFY_TOKEN=$(_existing WA_VERIFY_TOKEN || true)
if [[ -z "$VERIFY_TOKEN" ]]; then
  VERIFY_TOKEN=$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32)
  write_env WA_VERIFY_TOKEN "$VERIFY_TOKEN"
fi
say "A verify token was generated for the Meta handshake:"
printf '\n      %s%s%s\n\n' "$BOLD" "$VERIFY_TOKEN" "$RESET"
open_url "$APP_URL"
step "Settings → AI Sales Agent tab → WhatsApp Cloud API → Connect. Fill in:"
note "  Phone number ID       = $WA_PHONE_NUMBER_ID"
note "  Business account ID   = $WA_BUSINESS_ACCOUNT_ID"
note "  Access token          = (the token you just pasted)"
note "  Verify token          = $VERIFY_TOKEN"
note "  App secret            = (the App Secret from stage 2)"
step "Save. The toast should say 'WhatsApp credentials stored.'"
pause "Saved in the app? Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Webhook — point Meta at the Cloud Function"
say "Callback URL:"
printf '\n      %s%s%s\n\n' "$BOLD" "$WEBHOOK_URL" "$RESET"
open_url "https://developers.facebook.com/apps/${META_APP_ID}/whatsapp-business/wa-settings/"
step "WhatsApp → Configuration → Webhook → Edit: paste the Callback URL and the verify token above → Verify and save."
note "Verification only succeeds AFTER stage 5 — the function looks the token up in the saved credentials."
step "Under Webhook fields click Manage → subscribe to 'messages' (v22.0 or newest)."
if confirm "Did Meta report 'Verified' and is 'messages' subscribed?"; then :; else
  SKIPPED+=("Webhook not verified — check the function logs: firebase functions:log --only salesAgentWhatsAppWebhook")
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Template — enquiry_followup"
say "Dave's first outbound message after an email lead must be an approved template."
open_url "https://business.facebook.com/wa/manage/message-templates/"
step "Create template → Category: Utility → Name: enquiry_followup → Language: English (UK)."
step "Body � must match the code word for word (functions/src/salesAgent/channels/whatsapp.ts renderFallbackTemplate):"
note "  Hi {{1}}, it's Dave from Radlett Cars — thanks for your enquiry about the {{2}}. It's still available; happy to answer anything or sort a viewing. When suits?"
note "  Sample values: {{1}} = Sam, {{2}} = 2019 BMW 320d"
step "Submit. Approval is usually minutes to a few hours; Dave falls back to waiting for the customer to message first until it's approved."
pause "Template submitted? Press Enter."

finish
say "Test it: WhatsApp your own business number from another phone — the thread should appear in the Agent Inbox."
say "Logs: firebase functions:log --only salesAgentWhatsAppWebhook"
